name: style_builder_annotation
description: Contains the annotation for the style_builder package.
version: 1.0.0
repository: https://github.com/domain-centric/style_builder_annotation

environment:
  sdk: ^3.7.2

dependencies:
  
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
